apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: object-store-gateway
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: thanos-store
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: master-2020-02-13-adfef4b5
    store.observatorium.io/shard: shard-0
  name: observatorium-xyz-thanos-store-shard-0
  namespace: observatorium
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: object-store-gateway
      app.kubernetes.io/instance: observatorium-xyz
      app.kubernetes.io/name: thanos-store
      app.kubernetes.io/part-of: observatorium
      store.observatorium.io/shard: shard-0
  serviceName: observatorium-xyz-thanos-store-shard-0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: object-store-gateway
        app.kubernetes.io/instance: observatorium-xyz
        app.kubernetes.io/name: thanos-store
        app.kubernetes.io/part-of: observatorium
        app.kubernetes.io/version: master-2020-02-13-adfef4b5
        store.observatorium.io/shard: shard-0
    spec:
      containers:
      - args:
        - store
        - --data-dir=/var/thanos/store
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --experimental.enable-index-header
        - |
          --selector.relabel-config=
            - action: hashmod
              source_labels: ["__block_id"]
              target_label: shard
              modulus: 1
            - action: keep
              source_labels: ["shard"]
              regex: 0
        env:
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: thanos.yaml
              name: thanos-objectstorage
        image: quay.io/thanos/thanos:master-2020-02-13-adfef4b5
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /-/healthy
            port: 10902
            scheme: HTTP
          periodSeconds: 30
        name: thanos-store
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          periodSeconds: 5
        volumeMounts:
        - mountPath: /var/thanos/store
          name: data
          readOnly: false
      terminationGracePeriodSeconds: 120
      volumes:
      - emptyDir: {}
        name: data
  volumeClaimTemplates: null
