jobs:
  build:
    working_directory: /go/src/github.com/observatorium/configuration
    docker:
      - image: quay.io/coreos/jsonnet-ci
    steps:
      - checkout
      - run: find . -type f -not -path './vendor/*' \( -name '*.libsonnet' -o -name '*.jsonnet' \) | xargs -L1 jsonnetfmt --test
      - run: curl -o ./jb -L "https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/v0.2.0/jb-$(go env GOOS)-$(go env GOARCH)" && chmod +x ./jb
      - run: ./jb install
      - run: ./build.sh
      - run: git diff --exit-code

  tests:
    machine: true
    steps:
      - checkout
      - run: |
          ./tests/e2e.sh kind
          ./tests/e2e.sh deploy
          ./tests/e2e.sh test

  test-operator:
    machine: true
    steps:
      - checkout
      - run: |
          ./tests/e2e.sh kind
          ./tests/e2e.sh deploy-operator
          ./tests/e2e.sh test
  
  container-push:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login quay.io --username $DOCKER_USER --password-stdin
          make container-push

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - tests
      - test-operator
  tagged-master:
    jobs:
      - container-push:
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
  commit-master:
    jobs:
      - build
      - tests
      - test-operator
      - container-push:
          requires:
            - build
          filters:
            branches:
              only:
                - master
